dataset_root: /mnt/sda/Datasets/SLR-Reproduction/SignGraph/data/PHOENIX-2014-release/ 
dict_path: ./preprocess/phoenix2014/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: phoenix2014-groundtruth
